services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "yarn dev"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env

  postgres:
    image: postgres:17-alpine
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
