apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage-pvc
  labels:
    app: fcc-physics-events-backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs # Use CERN's default CephFS storage class
